-- MySQL Script generated by MySQL Workbench
-- Thu Jul 29 10:27:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema psis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema psis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psis` DEFAULT CHARACTER SET utf8 ;
USE `psis` ;

-- -----------------------------------------------------
-- Table `psis`.`consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`consultorio` (
  `nome` VARCHAR(90) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`documento` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `arquivo` BLOB NULL,
  `descricao` VARCHAR(145) NULL,
  PRIMARY KEY (`iddocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`historicofamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`historicofamiliar` (
  `idhistoricofamiliar` INT NOT NULL,
  `situacaoeconomica` VARCHAR(45) NULL,
  `costumes` VARCHAR(45) NULL,
  `educacaofamiliar` VARCHAR(45) NULL,
  `ambiente` VARCHAR(45) NULL,
  `pai` VARCHAR(45) NULL,
  `mae` VARCHAR(45) NULL,
  `irmaos` VARCHAR(45) NULL,
  `acontecimentos` VARCHAR(45) NULL,
  `mortes` VARCHAR(45) NULL,
  PRIMARY KEY (`idhistoricofamiliar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`infancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`infancia` (
  `idinfancia` INT NOT NULL,
  `primeirasrecordacoes` VARCHAR(45) NULL,
  `saude` VARCHAR(45) NULL,
  `relacionamentopais` VARCHAR(45) NULL,
  `relacionamentoirmaos` VARCHAR(45) NULL,
  `relacionamentocriancas` VARCHAR(45) NULL,
  `amizade` VARCHAR(45) NULL,
  `controleurinafezes` VARCHAR(45) NULL,
  `brincadeiras` VARCHAR(45) NULL,
  `brinquedos` VARCHAR(45) NULL,
  `papelbrincadeiras` VARCHAR(45) NULL,
  `fantasias` VARCHAR(45) NULL,
  `acontecimentos` VARCHAR(45) NULL,
  PRIMARY KEY (`idinfancia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`adolescencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`adolescencia` (
  `idadolescencia` INT NOT NULL,
  `sentimentoscomportamentos` VARCHAR(45) NULL,
  `mudancascorporais` VARCHAR(45) NULL,
  `relacionamentosamizades` VARCHAR(45) NULL,
  `jogospreferencias` VARCHAR(45) NULL,
  `estudos` VARCHAR(45) NULL,
  `trabalhos` VARCHAR(45) NULL,
  `experiencias` VARCHAR(45) NULL,
  PRIMARY KEY (`idadolescencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`saude` (
  `idsaude` INT NOT NULL AUTO_INCREMENT,
  `sono` VARCHAR(45) NULL,
  `sonhos` VARCHAR(45) NULL,
  `habitosalimentares` VARCHAR(45) NULL,
  `doencas` VARCHAR(45) NULL,
  `medicamentos` VARCHAR(45) NULL,
  PRIMARY KEY (`idsaude`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`trabalho` (
  `idtrabalho` INT NOT NULL,
  `inicio` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `usodinheiro` VARCHAR(45) NULL,
  `maisgosta_menosgosta` VARCHAR(45) NULL,
  `pedido` VARCHAR(45) NULL,
  PRIMARY KEY (`idtrabalho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`devafetivosexual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`devafetivosexual` (
  `iddevafetivosexual` INT NOT NULL,
  `comportamentos` VARCHAR(45) NULL,
  `quempartilhava` VARCHAR(45) NULL,
  `curiosidades` VARCHAR(45) NULL,
  `reacoes` VARCHAR(45) NULL,
  `mast` VARCHAR(45) NULL,
  `brincadeiras` VARCHAR(45) NULL,
  `experiencia` VARCHAR(45) NULL,
  `atitudes` VARCHAR(45) NULL,
  `expamizades` VARCHAR(45) NULL,
  `expintimidade` VARCHAR(45) NULL,
  `namoro` VARCHAR(45) NULL,
  `preocupacao` VARCHAR(45) NULL,
  PRIMARY KEY (`iddevafetivosexual`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`anamnese` (
  `idanamnese` INT NOT NULL AUTO_INCREMENT,
  `historicofamiliar_idhistoricofamiliar` INT NOT NULL,
  `infancia_idinfancia` INT NOT NULL,
  `adolescencia_idadolescencia` INT NOT NULL,
  `saude_idsaude` INT NOT NULL,
  `trabalho_idtrabalho` INT NOT NULL,
  `devafetivosexual_iddevafetivosexual` INT NOT NULL,
  PRIMARY KEY (`idanamnese`, `historicofamiliar_idhistoricofamiliar`, `infancia_idinfancia`, `adolescencia_idadolescencia`, `saude_idsaude`, `trabalho_idtrabalho`, `devafetivosexual_iddevafetivosexual`),
  INDEX `fk_anamnese_historicofamiliar1_idx` (`historicofamiliar_idhistoricofamiliar` ASC) VISIBLE,
  INDEX `fk_anamnese_infancia1_idx` (`infancia_idinfancia` ASC) VISIBLE,
  INDEX `fk_anamnese_adolescencia1_idx` (`adolescencia_idadolescencia` ASC) VISIBLE,
  INDEX `fk_anamnese_saude1_idx` (`saude_idsaude` ASC) VISIBLE,
  INDEX `fk_anamnese_trabalho1_idx` (`trabalho_idtrabalho` ASC) VISIBLE,
  INDEX `fk_anamnese_devafetivosexual1_idx` (`devafetivosexual_iddevafetivosexual` ASC) VISIBLE,
  CONSTRAINT `fk_anamnese_historicofamiliar1`
    FOREIGN KEY (`historicofamiliar_idhistoricofamiliar`)
    REFERENCES `psis`.`historicofamiliar` (`idhistoricofamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anamnese_infancia1`
    FOREIGN KEY (`infancia_idinfancia`)
    REFERENCES `psis`.`infancia` (`idinfancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anamnese_adolescencia1`
    FOREIGN KEY (`adolescencia_idadolescencia`)
    REFERENCES `psis`.`adolescencia` (`idadolescencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anamnese_saude1`
    FOREIGN KEY (`saude_idsaude`)
    REFERENCES `psis`.`saude` (`idsaude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anamnese_trabalho1`
    FOREIGN KEY (`trabalho_idtrabalho`)
    REFERENCES `psis`.`trabalho` (`idtrabalho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anamnese_devafetivosexual1`
    FOREIGN KEY (`devafetivosexual_iddevafetivosexual`)
    REFERENCES `psis`.`devafetivosexual` (`iddevafetivosexual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `foto` BLOB NULL,
  `dataNascimento` DATE NULL,
  `sexo` VARCHAR(1) NULL,
  `cpf` VARCHAR(14) NULL,
  `rg` VARCHAR(14) NULL,
  `observacao` VARCHAR(200) NULL,
  `celular` VARCHAR(11) NULL,
  `telefone` VARCHAR(10) NULL,
  `email` VARCHAR(100) NULL,
  `cep` VARCHAR(10) NULL,
  `cidade` VARCHAR(40) NULL,
  `estado` VARCHAR(20) NULL,
  `endereco` VARCHAR(100) NULL,
  `numero` VARCHAR(50) NULL,
  `complemento` VARCHAR(80) NULL,
  `bairro` VARCHAR(80) NULL,
  `nomeResponsavel` VARCHAR(90) NULL,
  `dataResponsavel` DATE NULL,
  `cpfResponsavel` VARCHAR(14) NULL,
  `consultorioId` INT NOT NULL,
  `documento_iddocumento` INT NOT NULL,
  `anamnese_idanamnese` INT NOT NULL,
  PRIMARY KEY (`id`, `consultorioId`, `documento_iddocumento`, `anamnese_idanamnese`),
  INDEX `fk_paciente_consultorio_idx` (`consultorioId` ASC) VISIBLE,
  INDEX `fk_paciente_documento1_idx` (`documento_iddocumento` ASC) VISIBLE,
  INDEX `fk_paciente_anamnese1_idx` (`anamnese_idanamnese` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_consultorio`
    FOREIGN KEY (`consultorioId`)
    REFERENCES `psis`.`consultorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_documento1`
    FOREIGN KEY (`documento_iddocumento`)
    REFERENCES `psis`.`documento` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_anamnese1`
    FOREIGN KEY (`anamnese_idanamnese`)
    REFERENCES `psis`.`anamnese` (`idanamnese`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`agendamento` (
  `idagendamento` INT NOT NULL,
  `dataConsulta` VARCHAR(45) NULL,
  `horarioInicio` VARCHAR(45) NULL,
  `horarioTermino` VARCHAR(45) NULL,
  `motivo` VARCHAR(45) NULL,
  `link` VARCHAR(85) NULL,
  `agendamentocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idagendamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`sessao` (
  `idsessao` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL NULL,
  `data` DATE NULL,
  `dataPagamento` DATE NULL,
  `anotacoes` VARCHAR(450) NULL,
  `statuspagamento` VARCHAR(45) NULL,
  `agendamento_idagendamento` INT NOT NULL,
  `paciente_id` INT NOT NULL,
  PRIMARY KEY (`idsessao`, `agendamento_idagendamento`, `paciente_id`),
  INDEX `fk_sessao_agendamento1_idx` (`agendamento_idagendamento` ASC) VISIBLE,
  INDEX `fk_sessao_paciente1_idx` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `fk_sessao_agendamento1`
    FOREIGN KEY (`agendamento_idagendamento`)
    REFERENCES `psis`.`agendamento` (`idagendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sessao_paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `psis`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `consultorio_id` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `consultorio_id`),
  INDEX `fk_usuario_consultorio1_idx` (`consultorio_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_consultorio1`
    FOREIGN KEY (`consultorio_id`)
    REFERENCES `psis`.`consultorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psis`.`despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psis`.`despesa` (
  `iddespesa` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  `valor` DECIMAL NULL,
  `vencimento` DATE NULL,
  `categoria` VARCHAR(45) NULL,
  `statuspagamento` VARCHAR(45) NULL,
  `consultorio_id` INT NOT NULL,
  PRIMARY KEY (`iddespesa`, `consultorio_id`),
  INDEX `fk_despesa_consultorio1_idx` (`consultorio_id` ASC) VISIBLE,
  CONSTRAINT `fk_despesa_consultorio1`
    FOREIGN KEY (`consultorio_id`)
    REFERENCES `psis`.`consultorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
